<?php

/**
 * @file
 * Headless Authoring eXperience, all we do is accept calls and make things
 *   haxable in the first place.
 */

/**
 * Implememts hook_preprocess_hook().
 *
 * Add cms-hax tag and related markup as wrapper to body field.
 */
function hax_preprocess_field(&$vars) {

  // Supporting attachments handled in hax_page_attachments().

  // Allow for cache variability based on route name so this can be handled
  // evaluated separately for the view and the hax mode tabs.
  $vars['#cache']['contexts'][] = 'route.name';

  if (!hax_is_current_route_supported()) {
    return;
  }

  $entity_type = $vars['element']['#object']->getEntityTypeId();
  $bundle = $vars['element']['#object']->bundle();
  $view_mode = $vars['element']['#view_mode'];

  if ($vars['field_name'] == 'body' && $entity_type == 'node' && $view_mode == 'full'
    && \Drupal::config('hax.settings')->get('hax_autoload_element_node_view')) {

    // Generate autoload list.
    $elementstring = \Drupal::config('hax.settings')->get('hax_autoload_element_list');
    // Blow up based on space.
    $elements = explode(' ', $elementstring);
    $components = '';
    foreach ($elements as $element) {
      // sanity check
      if (!empty($element)) {
        $components .= '<' . $element . ' slot="autoloader">' . '</' . $element . '>';
      }
    }

    $appStoreConnection = json_encode(['url' => base_path() . 'hax-app-store/' . \Drupal::csrfToken()->get()]);

    // Get the NID from current path.
    $request = \Drupal::request();
    $current_path = $request->getPathInfo();
    $path_args = explode('/', $current_path);
    $node_id = $path_args[2];

    // Add <cms-hax> tag around body markup.

    // DRUPAL is stripping tag in #prefix and #suffix...
    // see Drupal\Component\Utility\Xss
    //$vars['items'][0]['content']['#prefix'] = '
    //  <cms-hax open-default end-point="' . base_path() . 'hax-node-save/' . $node_id .  '/' . \Drupal::csrfToken()->get() . '" body-offset-left="' . \Drupal::config('hax.settings')->get('hax_offset_left') . '" app-store-connection=' . "'" . json_encode($appStoreConnection) . "'" . '>'
    //  . $components;
    //$vars['items'][0]['content']['#suffix'] = '</cms-hax>';

    // TODO Not ideal, but we've fallen back to using the body text instead of
    // prefix/suffix due to filtering. This will go through the node's selected
    // text format for render.
    $vars['items'][0]['content']['#text'] = '
      <cms-hax open-default end-point="' . base_path() . 'hax-node-save/' . $node_id .  '/' . \Drupal::csrfToken()->get() . '" body-offset-left="' . \Drupal::config('hax.settings')->get('hax_offset_left') . '" app-store-connection=' . "'" . $appStoreConnection . "'" . '>'
      . $components . $vars['items'][0]['content']['#text'] . '</cms-hax>';

  }

}

/**
 * Implements hook_hax_app_store().
 */
function hax_hax_app_store() {

  $config = \Drupal::config('hax.settings');

  $hax = new \Drupal\hax\HAXService;
  $apikeys = array();
  $baseApps = $hax->baseSupportedApps();
  foreach ($baseApps as $key => $app) {

    if ($config->get('hax_' . $key . '_key') != '') {
      $apikeys[$key] = $config->get('hax_' . $key . '_key');
    }

  }
  $json = $hax->loadBaseAppStore($apikeys);
  // pull in the core ones we supply
  if (\Drupal::moduleHandler()->moduleExists('file_entity') && \Drupal::moduleHandler()->moduleExists('rest')) {
    $tmp = json_decode(_hax_site_connection());
    array_push($json, $tmp);
  }
  return $json;
}

/**
 * Connection details for this site. This is where
 * all the really important stuff is that will
 * make people freak out.
 */
function _hax_site_connection() {
  global $base_url;
  $parts = explode('://', $base_url);
  // built in support when file_entity and restws is in place
  $json = '{
    "details": {
      "title": "' . t('Internal files') . '",
      "icon": "perm-media",
      "color": "light-blue",
      "author": "Drupal",
      "description": "Drupal site integration for HAX",
      "tags": ["media", "drupal"]
    },
    "connection": {
      "protocol": "' . $parts[0] . '",
      "url": "' . $parts[1] . '",
      "operations": {
        "browse": {
          "method": "GET",
          "endPoint": "file.json",
          "pagination": {
            "style": "link",
            "props": {
              "first": "page.first",
              "next": "page.next",
              "previous": "page.previous",
              "last": "page.last"
            }
          },
          "search": {
          },
          "data": {
          },
          "resultMap": {
            "defaultGizmoType": "image",
            "items": "list",
            "preview": {
              "title": "name",
              "details": "mime",
              "image": "url",
              "id": "uuid"
            },
            "gizmo": {
              "source": "url",
              "id": "uuid",
              "title": "name",
              "type": "type"
            }
          }
        },
        "add": {
          "method": "POST",
          "endPoint": "hax-file-save/' . \Drupal::csrfToken()->get() . '",
          "acceptsGizmoTypes": [
            "image",
            "video",
            "audio",
            "pdf",
            "svg",
            "document",
            "csv"
          ],
          "resultMap": {
            "item": "data.file",
            "defaultGizmoType": "image",
            "gizmo": {
              "source": "url",
              "id": "uuid"
            }
          }
        }
      }
    }
  }';
  return $json;
}

/**
 * Implements hook_page_attachments().
 *
 * Load all attachments for this page.
 */

function hax_page_attachments(array &$attachments) {

  // Need this to execute on variations of route.name to support view and
  // hax mode tab variation.
  $vars['#cache']['contexts'][] = 'route.name';

  if (!hax_is_current_route_supported()) {
    return;
  }

  // Fake a component to get it into the head of the document, heavy weighting
  $component = new \stdClass();
  $component->machine_name = 'cms-hax';
  $component->file = 'libraries/webcomponents/polymer/bower_components/cms-hax/cms-hax.html';
  $element = [
    '#tag' => 'link', // The #tag is the html tag
    '#attributes' => [ // Set up an array of attributes inside the tag
      'href' => base_path() . $component->file,
      'rel' => 'import',
    ],
  ];
  $attachments['#attached']['html_head'][] = [$element, 'webcomponent-' . $component->machine_name];

  // TODO do we need the autoload attachments here, too?

  // Generate autoload list.
  $elementstring = \Drupal::config('hax.settings')->get('hax_autoload_element_list');
  // Blow up based on space.
  $elements = explode(' ', $elementstring);
  $components = '';
  foreach ($elements as $element) {
    $component = new \stdClass();
    $component->machine_name = $element;
    // Pull in from webcomponents location.
    $component->file = 'libraries/webcomponents/polymer/bower_components/' . $element . '/' . $element . '.html';
    $element = [
      '#tag' => 'link', // The #tag is the html tag
      '#attributes' => [ // Set up an array of attributes inside the tag
        'href' => base_path() . $component->file,
        'rel' => 'import',
      ],
    ];

    // Add components to html_head via $vars.
    $attachments['#attached']['html_head'][] = [$element, 'webcomponent-' . $component->machine_name];
  }

}

/**
 * Identify whether the current route is supported for HAX deployment.
 *
 * @return bool
 *   TRUE if the current route is supported.
 */
function hax_is_current_route_supported() {

  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($route_name == 'hax.node_form') {
    return TRUE;
  }

  return FALSE;
}


